#ifndef __GAME_TITLE_H__
#define __GAME_TITLE_H__
/* Translate table build from this xml file :
   https://gitlab.incom.co/libretro/mame/-/blob/888cf1033a543f5b36db69417aa8dc68113add64/hash/videopac.xml
*/

unsigned char *game_title[][2] = {
   {"VP_40.BIN", "4 IN 1 ROW     "},
   {"VP_40_F.BIN", "4 EN 1 LIGNE   "},
   {"VP_32.BIN", "A LABYRINTH GAM"},
   {"VP_04.BIN", "AIR-SEA WAR / B"},
   {"VP_03.BIN", "AMERICAN FOOTBA"},
   {"O2_45.BIN", "ATTACK OF THE T"},
   {"VP_48.BIN", "BACKGAMMON     "},
   {"BR_54.BIN", "BAL㏠TRAVESSO!"},
   {"VP_54.BIN", "LOONY BALLOON  "},
   {"BR_58.BIN", "BAR㏠VERMELHO!"},
   {"PR_AIRBATTLE.BIN", "AIR BATTLE     "},
   {"PR_AIRBATTLE_ALT.BIN", "AIR BATTLE     "},
   {"VP_08.BIN", "BASEBALL       "},
   {"VP_26.BIN", "BASKET GAME    "},
   {"VP_30.BIN", "BATTLEFIELD    "},
   {"VP_05.BIN", "BLACKJACK      "},
   {"VP_05_F.BIN", "BLACKJACK      "},
   {"VP_57.BIN", "BLOBBERS       "},
   {"BR_55.BIN", "BURACO NEGRO!  "},
   {"VP_55.BIN", "NEUTRON STAR   "},
   {"VP_19.BIN", "CATCH THE BALL "},
   {"BR_19.BIN", "O MALABARISTA! "},
   {"VP_C7010.BIN", "CHESS MODULE   "},
   {"VP_17.BIN", "CHINESE LOGIC  "},
   {"BR_17.BIN", "DESAFIO CHIN   "},
   {"BR_CLAY-PIGEON.BIN", "CLAY PIGEON!   "},
   {"BR_COMANDO-NOTURNO.BIN", "COMANDO NOTURNO"},
   {"PR_NIGHTFIGHTER.BIN", "NIGHTFIGHTER   "},
   {"VP_09.BIN", "COMPUTER PROGRA"},
   {"O2_06.BIN", "COMPUTER INTRO!"},
   {"VP_41.BIN", "CONQUEST OF THE"},
   {"VP_11.BIN", "COSMIC CONFLICT"},
   {"VP_11_ALT.BIN", "COSMIC CONFLICT"},
   {"VP_11_F.BIN", "GUERRE DE L'ESP"},
   {"O2_11.BIN", "COSMIC CONFLICT"},
   {"VP_44.BIN", "CRAZY CHASE    "},
   {"VP_29.BIN", "DAM BUSTER     "},
   {"VP_29_F.BIN", "LE MûR MAGIQUE "},
   {"VP_16.BIN", "DEPTH CHARGE / "},
   {"BR_16.BIN", "BOMBARDEIO SUBM"},
   {"VP_35.BIN", "ELECTRONIC BILL"},
   {"VP_35_F.BIN", "BILLARD AM钉CA"},
   {"VP_36.BIN", "ELECTRONIC ICE "},
   {"VP_36_F.BIN", "FOOTBALL ELECTR"},
   {"VP_27.BIN", "ELECTRONIC TABL"},
   {"VP_28.BIN", "ELECTRONIC VOLL"},
   {"VP_28_F.BIN", "VOLLEYBALL     "},
   {"VP_24.BIN", "FLIPPER GAME   "},
   {"VP_24_F.BIN", "FLIPPER        "},
   {"VP_39.BIN", "FREEDOM FIGHTER"},
   {"VP_10.BIN", "GOLF           "},
   {"O2_10.BIN", "COMPUTER GOLF! "},
   {"VP_14.BIN", "GUNFIGHTER     "},
   {"O2_16.BIN", "SHOWDOWN IN 210"},
   {"VP_33.BIN", "JUMPING ACROBAT"},
   {"VP_33_ALT.BIN", "JUMPING ACROBAT"},
   {"O2_43.BIN", "P.T. BARNUM'S A"},
   {"O2_47.BIN", "KILLER BEES!   "},
   {"PR_KILLERBEES.BIN", "KILLER BEES!   "},
   {"PR_KILLERBEES_ALT.BIN", "KILLER BEES!   "},
   {"VP_23.BIN", "LAS VEGAS GAMBL"},
   {"VP_23_F.BIN", "LAS VEGAS      "},
   {"VP_18.BIN", "LASER WAR      "},
   {"VP_18_F.BIN", "GUERRE LAZER   "},
   {"O2_14.BIN", "INVADERS FROM H"},
   {"VP_07.BIN", "MATHEMATICIAN /"},
   {"VP_07_F.BIN", "MATH鍁TICIEN /"},
   {"VP_37.BIN", "MONKEYSHINES   "},
   {"VP_45.BIN", "MORSE          "},
   {"VP_45_F.BIN", "MORSE          "},
   {"VP_38.BIN", "MUNCHKIN       "},
   {"O2_35.BIN", "K.C. MUNCHKIN! "},
   {"VP_31.BIN", "MUSICIAN       "},
   {"VP_A.BIN", "NEWSCASTER     "},
   {"O2_33.BIN", "KEYBOARD CREATI"},
   {"O2_39.BIN", "NIMBLE NUMBERS "},
   {"O2_19.BIN", "OUT OF THIS WOR"},
   {"VP_02.BIN", "PAIRS / SPACE R"},
   {"O2_07.BIN", "MATCHMAKER! / B"},
   {"VP_53.BIN", "PHANTOM HOUSE  "},
   {"VP_43.BIN", "PICKAXE PETE   "},
   {"VP_13.BIN", "PLAYSCHOOL MATH"},
   {"O2_48.BIN", "POWER LORDS    "},
   {"O2_48_ALT.BIN", "POWER LORDS    "},
   {"VP_01.BIN", "RACE / SPIN-OUT"},
   {"VP_01_F.BIN", "COURSE DE VOITU"},
   {"VP_15.BIN", "SAMURAI        "},
   {"O2_21.BIN", "DYNASTY!       "},
   {"VP_34.BIN", "SATELLITE ATTAC"},
   {"O2_30.BIN", "UFO!           "},
   {"VP_21.BIN", "SECRET OF THE P"},
   {"BR_21.BIN", "O SEGREDO DO FA"},
   {"O2_38.BIN", "SID THE SPELLBI"},
   {"VP_25.BIN", "SKIING         "},
   {"VP_25_F.BIN", "SKI            "},
   {"VP_22.BIN", "SPACE MONSTER  "},
   {"VP_20.BIN", "STONE SLING    "},
   {"O2_41.BIN", "SMITHEREENS!   "},
   {"VP_50.BIN", "SUPER BEE      "},
   {"BR_50.BIN", "SUPER BEE!     "},
   {"VP_12.BIN", "TAKE THE MONEY "},
   {"VP_12_F.BIN", "PRENDRE L'ARGEN"},
   {"VP_46.BIN", "THE GREAT WALL "},
   {"BR_46.BIN", "WALL STREET    "},
   {"VP_47.BIN", "THE MOUSING CAT"},
   {"VP_47_F.BIN", "CHAT ET SOURIS "},
   {"VP_42.BIN", "THE QUEST FOR T"},
   {"VP_42_F.BIN", "LA QUꔅ DES AN"},
   {"SP0256B-019.BIN", "THE VOICE      "},
   {"VP_06.BIN", "TEN PIN BOWLING"},
   {"VP_06_F.BIN", "JEU DE QUILLES "},
   {"VP_49.BIN", "TURTLES        "},
   {"O2_46.BIN", "TURTLES!       "},
   {"O2_40.BIN", "TYPE & TELL!   "},
   {"IM_ATLANTIS.BIN", "ATLANTIS       "},
   {"JO_VXT_A08.BIN", "CHEZ MAXIME    "},
   {"IM_DEMON-ATTACK.BIN", "DEMON ATTACK   "},
   {"JO_JFT_D03.BIN", "DES CHIFFRES ET"},
   {"PB_FROGGER.BIN", "FROGGER        "},
   {"BR_FROGGER.BIN", "FROGGER        "},
   {"PR_LINGUADUC.BIN", "LINGUADUC      "},
   {"PR_MISSION-IMPOSSIBLE.BIN", "MISSAO IMPOSSIB"},
   {"PB_POPEYE.BIN", "POPEYE         "},
   {"BR_POPEYE.BIN", "POPEYE         "},
   {"PB_Q-BERT.BIN", "Q*BERT         "},
   {"PB_SUPER-COBRA.BIN", "SUPER COBRA    "},
   {"BR_SUPER-COBRA.BIN", "SUPER COBRA    "},
   {"JO_VXT_A07.BIN", "SYRACUSE       "},
   {"CSV1.BIN", "VERKEHRSSPIELE "},
   {"VP_V.BIN", "KINDER IM VERKE"},
   {"CSV2.BIN", "VERKEHRSSPIELE "},
   {"PR_BASTION.BIN", "BASTION        "},
   {"PR_HIMALAYA.BIN", "HIMALAYA       "},
   {"PR_INTERPOL.BIN", "INTERPOL       "},
   {"PR_MARTIAN-THREAT.BIN", "MARTIAN THREAT "},
   {"PR_MARTIAN-THREAT_ALT.BIN", "MARTIAN THREAT "},
   {"PR_PINBALL.BIN", "PINBALL!       "},
   {"PR_PLAYTAG.BIN", "PLAY TAG       "},
   {"PR_ROBOT-CITY.BIN", "ROBOT CITY     "},
   {"TESTCART.BIN", "SERVICE TEST CA"},
   {"PR_SHARK-HUNTER.BIN", "SHARK HUNTER   "},
   {"SOUNDTOOL.BIN", "SOUND TOOL     "},
   {"PR_SPIDERMAN.BIN", "SPIDER-MAN     "},
   {"PR_SPIDERMAN_ALT.BIN", "SPIDER-MAN     "},
   {"PR_TERRAHAWKS2.BIN", "TERRAHAWKS     "},
   {"PR_SHERLOCK.BIN", "THE ADVENTURES "},
   {"PR_TUTANKHAM.BIN", "TUTANKHAM      "},
   {"VP_58PL.BIN", "AIR BATTLE     "},
   {"JO_JFA_E03.BIN", "BASKET BOWLING+"},
   {"VP_06PL.BIN", "TEN PIN BOWLING"},
   {"JO_JXA_D03.BIN", "BILLARD+       "},
   {"VP_35PL.BIN", "BILLIARD       "},
   {"PR_CLAY-PIGEON_PL.BIN", "CLAY PIGEON    "},
   {"PR_CLAY-PIGEON_PL_ALT.BIN", "CLAY PIGEON    "},
   {"VP_11PL.BIN", "COSMIC CONFLICT"},
   {"VP_11PL_F.BIN", "COSMOS+        "},
   {"JO_JXT_C07.BIN", "DEMON ATTACK+  "},
   {"JO_JXT_C05.BIN", "EXOJET+        "},
   {"JO_JFA_D01.BIN", "FLIPPER+       "},
   {"VP_24PL.BIN", "FLIPPER GAME   "},
   {"VP_39PL.BIN", "FREEDOM FIGHTER"},
   {"VP_52PL.BIN", "KILLER BEES    "},
   {"VP_52PL_F.BIN", "LA RUCHE INFERN"},
   {"JO_JFT_A10.BIN", "LE TRESOR ENGLO"},
   {"VP_54PL.BIN", "LOONY BALLOON  "},
   {"VP_55PL", "NEUTRON STAR   "},
   {"VP_53PL.BIN", "NIGHTMARE      "},
   {"VP_43PL.BIN", "PICKAXE PETE   "},
   {"VP_01PL.BIN", "RACE / SPIN-OUT"},
   {"VP_01PL_F.BIN", "GRAND PRIX+    "},
   {"VP_34PL.BIN", "SATELLITE ATTAC"},
   {"VP_20PL.BIN", "STONE SLING    "},
   {"VP_51PL.BIN", "TERRAHAWKS     "},
   {"VP_59PL.BIN", "HELICOPTER RESC"},
   {"VP_C7420.BIN", "HOME COMPUTER M"},
   {"JO_JXT_E05.BIN", "MOTO-CRASH+    "},
   {"VP_56PL.BIN", "NORSEMAN       "},
   {"VP_60PL.BIN", "TRANS AMERICAN "},
   {"O3_45.BIN", "ATTACK OF THE T"},
   {"O3_08.BIN", "BASEBALL!      "},
   {"O3_FLASH.BIN", "FLASH POINT    "},
   {"O3_36.BIN", "FREEDOM FIGHTER"},
   {"O3_47.BIN", "KILLER BEES!   "},
   {"O3_TERMINAL.BIN", "TERMINAL PROGRA"},
   {"AMOKPD.BIN", "AMOK!          "},
   {"NEW_CALCULATOR.BIN", "CALCULATOR!    "},
   {"DRACE_RC04_NTSC.BIN", "DEATH RACE     "},
   {"DRACE_RC04_PAL.BIN", "DEATH RACE     "},
   {"KTAA.BIN", "KILL THE ATTACK"},
   {"MRROBOTO.BIN", "MR. ROBOTO!    "},
   {"PLANDER.BIN", "PLANET LANDER  "},
   {"NEW_PONG_ALL.BIN", "PONG FOR VIDEOP"},
   {"PPP.BIN", "PUZZLE PIECE PA"},
   {"RASH.BIN", "RASH           "},
   {"NEW_ROUTE66.BIN", "ROUTE 66       "},
   {"PAL_FLASHPOINT.BIN", "FLASH POINT    "},
   {"", ""}
};
#endif